# Generated by Django 3.2.6 on 2021-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
